//state de producto

export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

//state papra pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';

export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'